/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the currently authenticated user's information from the database.
         *     This endpoint validates the Supabase JWT and returns the user record.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search locations by weather criteria
         * @description Searches for grid points matching the specified weather criteria and returns scored results.
         *
         *     **Date Range Limits:**
         *     - Ranges up to 30 days: Processed normally
         *     - Ranges 31-90 days: Processed with a warning in response
         *     - Ranges over 90 days: Rejected with DATE_RANGE_TOO_LARGE error
         *
         *     **Scoring:**
         *     - Only filters you explicitly provide are used in scoring
         *     - Each filter is weighted equally
         *     - Results are sorted by score descending
         */
        post: operations["searchWeather"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather/grid-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all grid points
         * @description Returns all searchable grid points for map display. Used to populate the
         *     map with location markers before a search is performed.
         *
         *     Grid points are spaced approximately 0.25° apart (~17 miles) for dense
         *     coverage across the continental USA.
         */
        get: operations["getGridPoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather/grid-points/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get weather detail for a grid point
         * @description Returns detailed weather data for a specific grid point and date range.
         */
        get: operations["getGridPointWeather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather/nearest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find nearest grid point
         * @description Given arbitrary coordinates, returns the nearest grid point.
         *     Useful for snapping user-selected map locations to the grid.
         */
        get: operations["findNearestGridPoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all saved searches
         * @description Returns all saved searches for the authenticated user.
         */
        get: operations["getSavedSearches"];
        put?: never;
        /**
         * Create a saved search
         * @description Saves a new weather search configuration.
         *
         *     **Rate Limit:** 30 requests/hour per user for save operations.
         */
        post: operations["createSavedSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a saved search
         * @description Returns a specific saved search by ID.
         */
        get: operations["getSavedSearch"];
        /**
         * Update a saved search
         * @description Updates an existing saved search. Users can only update their own searches.
         */
        put: operations["updateSavedSearch"];
        post?: never;
        /**
         * Delete a saved search
         * @description Deletes a saved search. Users can only delete their own searches.
         */
        delete: operations["deleteSavedSearch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all electrical configurations
         * @description Returns all saved electrical configurations for the authenticated user.
         */
        get: operations["getElectricalConfigs"];
        put?: never;
        /**
         * Create an electrical configuration
         * @description Creates a new electrical system configuration.
         *
         *     **Rate Limit:** 30 requests/hour per user for save operations.
         *
         *     There is no limit on the number of configurations a user can save.
         */
        post: operations["createElectricalConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an electrical configuration
         * @description Returns a specific electrical configuration by ID.
         */
        get: operations["getElectricalConfig"];
        /**
         * Update an electrical configuration
         * @description Updates an existing electrical configuration. Users can only update their own configs.
         */
        put: operations["updateElectricalConfig"];
        post?: never;
        /**
         * Delete an electrical configuration
         * @description Deletes an electrical configuration. Users can only delete their own configs.
         */
        delete: operations["deleteElectricalConfig"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get resources
         * @description Returns admin-curated resources, optionally filtered by category.
         *
         *     Resources are curated by admins only. Community submissions are not
         *     available in MVP.
         */
        get: operations["getResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a resource
         * @description Returns a specific resource by ID.
         */
        get: operations["getResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponse: {
            /** @example true */
            success: boolean;
        };
        ErrorResponse: {
            /** @example false */
            success: boolean;
            error: {
                /**
                 * @example VALIDATION_ERROR
                 * @enum {string}
                 */
                code: "VALIDATION_ERROR" | "AUTHENTICATION_REQUIRED" | "INVALID_CREDENTIALS" | "TOKEN_EXPIRED" | "RESOURCE_NOT_FOUND" | "DUPLICATE_RESOURCE" | "RATE_LIMITED" | "DATE_RANGE_TOO_LARGE" | "DATE_RANGE_WARNING" | "WEATHER_API_ERROR" | "INTERNAL_ERROR";
                /** @example Invalid email format */
                message: string;
                details?: {
                    field?: string;
                    message?: string;
                }[];
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description Precipitation types as tracked by the National Weather Service:
         *     - `none`: No precipitation
         *     - `rain`: Liquid precipitation
         *     - `snow`: Frozen precipitation (snowflakes)
         *     - `sleet`: Ice pellets formed from frozen raindrops
         *     - `freezing_rain`: Rain that freezes on contact with surfaces
         *     - `hail`: Large ice pellets from thunderstorms
         *     - `drizzle`: Light, fine rain
         *     - `thunderstorms`: Rain with thunder/lightning
         *     - `ice_pellets`: Small, translucent ice particles
         *     - `fog`: Low visibility due to water droplets in air
         *     - `mist`: Light fog with better visibility
         *     - `mixed`: Multiple precipitation types
         * @enum {string}
         */
        PrecipitationType: "none" | "rain" | "snow" | "sleet" | "freezing_rain" | "hail" | "drizzle" | "thunderstorms" | "ice_pellets" | "fog" | "mist" | "mixed";
        /**
         * @description Weather criteria for location search. All filters are optional.
         *     Only filters explicitly provided are used in score calculation.
         */
        WeatherFilters: {
            /**
             * @description Minimum temperature in °F
             * @example 65
             */
            tempMin?: number;
            /**
             * @description Maximum temperature in °F
             * @example 80
             */
            tempMax?: number;
            /**
             * @description Maximum humidity percentage
             * @example 50
             */
            humidityMax?: number;
            /**
             * @description Maximum wind speed in mph
             * @example 15
             */
            windSpeedMax?: number;
            /**
             * @description Maximum precipitation chance percentage
             * @example 20
             */
            precipChanceMax?: number;
            /**
             * @description List of acceptable precipitation types. If not specified, all types are acceptable.
             * @example [
             *       "none",
             *       "drizzle"
             *     ]
             */
            precipTypesAllowed?: components["schemas"]["PrecipitationType"][];
            /**
             * @description List of precipitation types to exclude from results
             * @example [
             *       "snow",
             *       "hail",
             *       "freezing_rain"
             *     ]
             */
            precipTypesExcluded?: components["schemas"]["PrecipitationType"][];
            /**
             * @description Maximum Air Quality Index value
             * @example 50
             */
            aqiMax?: number;
        };
        DateRange: {
            /**
             * Format: date
             * @description Start date (ISO 8601)
             * @example 2025-03-01
             */
            startDate: string;
            /**
             * Format: date
             * @description End date (ISO 8601)
             * @example 2025-03-31
             */
            endDate: string;
        };
        /**
         * @description A pre-computed grid point for weather data. Grid points are spaced approximately
         *     0.25° apart (~17 miles), providing dense coverage across the continental USA.
         *     When users select a location on the map, it snaps to the nearest grid point.
         */
        GridPoint: {
            /**
             * Format: uuid
             * @description Unique identifier for this grid point
             */
            id: string;
            /**
             * Format: double
             * @description Latitude in decimal degrees
             * @example 32.2226
             */
            latitude: number;
            /**
             * Format: double
             * @description Longitude in decimal degrees
             * @example -110.9747
             */
            longitude: number;
            /**
             * @description Name of nearest city/town for display purposes
             * @example Tucson
             */
            nearestCity?: string;
            /**
             * @description Two-letter state code
             * @example AZ
             */
            state: string;
            /**
             * @description Geographic region for filtering
             * @example southwest
             * @enum {string}
             */
            region?: "northeast" | "southeast" | "midwest" | "southwest" | "west" | "pacific_northwest";
        };
        WeatherSearchResult: {
            gridPoint: components["schemas"]["GridPoint"];
            /**
             * @description Overall match score (0-100). Calculated as the average of individual
             *     filter scores, considering only filters the user explicitly set.
             * @example 92
             */
            score: number;
            /**
             * @description Source of weather data:
             *     - `forecast`: NWS forecast data (typically 7-14 days out)
             *     - `historical`: Historical average data
             *     - `mixed`: Combination of forecast and historical for longer date ranges
             * @enum {string}
             */
            dataType: "forecast" | "historical" | "mixed";
            /** @description Individual scores for each filter criterion */
            breakdown: {
                temperature?: components["schemas"]["FilterScore"];
                humidity?: components["schemas"]["FilterScore"];
                wind?: components["schemas"]["FilterScore"];
                precipitation?: components["schemas"]["FilterScore"];
                aqi?: components["schemas"]["FilterScore"];
            };
        };
        FilterScore: {
            /** @description Score for this specific filter (0-100) */
            score: number;
            /** @description Actual average value for this metric */
            value: number;
            /** @description Unit of measurement */
            unit?: string;
        };
        DailyWeather: {
            /** Format: date */
            date: string;
            /**
             * @description Whether this day's data is from forecast or historical averages
             * @enum {string}
             */
            dataType: "forecast" | "historical";
            /** @description High temperature in °F */
            tempHigh: number;
            /** @description Low temperature in °F */
            tempLow: number;
            /** @description Average humidity percentage */
            humidity: number;
            /** @description Average wind speed in mph */
            windSpeed: number;
            /**
             * @description Predominant wind direction
             * @enum {string}
             */
            windDirection?: "N" | "NE" | "E" | "SE" | "S" | "SW" | "W" | "NW";
            /** @description Precipitation chance percentage */
            precipChance: number;
            precipType: components["schemas"]["PrecipitationType"];
            /** @description Air Quality Index value */
            aqi: number;
            /**
             * @description EPA AQI category
             * @enum {string}
             */
            aqiCategory: "Good" | "Moderate" | "Unhealthy for Sensitive Groups" | "Unhealthy" | "Very Unhealthy" | "Hazardous";
        };
        SavedSearch: {
            /** Format: uuid */
            id: string;
            /**
             * @description User-defined title for the search
             * @example Spring 2025 Southwest Trip
             */
            title: string;
            filters: components["schemas"]["WeatherFilters"];
            dateRange: components["schemas"]["DateRange"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Device: {
            /**
             * @description Device name
             * @example Fridge
             */
            name: string;
            /**
             * @description Power consumption in watts
             * @example 50
             */
            watts: number;
            /**
             * @description Average hours of use per day
             * @example 24
             */
            hoursPerDay: number;
        };
        BatteryConfig: {
            /**
             * @description Battery chemistry type
             * @enum {string}
             */
            type: "lead-acid" | "agm" | "lithium";
            /**
             * @description Capacity in amp-hours (Ah)
             * @example 200
             */
            capacity: number;
            /**
             * @description System voltage
             * @example 12
             * @enum {integer}
             */
            voltage: 12 | 24 | 48;
            /**
             * @description Number of batteries
             * @example 2
             */
            quantity: number;
        };
        SolarConfig: {
            /**
             * @description Wattage per panel
             * @example 200
             */
            panelWatts: number;
            /**
             * @description Number of panels
             * @example 2
             */
            quantity: number;
        };
        InverterConfig: {
            /**
             * @description Inverter wattage capacity
             * @example 2000
             */
            watts: number;
            /**
             * @description Inverter wave type
             * @example pure-sine
             * @enum {string}
             */
            type: "modified-sine" | "pure-sine";
        };
        ElectricalConfigData: {
            /** @description List of electrical devices */
            devices?: components["schemas"]["Device"][];
            batteries?: components["schemas"]["BatteryConfig"];
            solar?: components["schemas"]["SolarConfig"];
            inverter?: components["schemas"]["InverterConfig"];
        };
        ElectricalConfig: {
            /** Format: uuid */
            id: string;
            /**
             * @description User-defined title for the configuration
             * @example Current Van Setup
             */
            title: string;
            configData: components["schemas"]["ElectricalConfigData"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description Category of the resource
         * @enum {string}
         */
        ResourceCategory: "youtube" | "facebook" | "reddit" | "forum" | "repair" | "gear" | "apps" | "other";
        Resource: {
            /** Format: uuid */
            id: string;
            /** @example Will Prowse Solar Reviews */
            title: string;
            /**
             * Format: uri
             * @example https://youtube.com/@WillProwse
             */
            url: string;
            category: components["schemas"]["ResourceCategory"];
            /** @example In-depth solar and electrical reviews for van and RV systems */
            description?: string;
        };
        Pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    };
    responses: {
        /** @description Missing or invalid authentication token */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "AUTHENTICATION_REQUIRED",
                 *         "message": "Valid authentication token required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimitError: {
            headers: {
                /** @description Seconds until rate limit resets */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "Too many requests. Please try again later."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "RESOURCE_NOT_FOUND",
                 *         "message": "The requested resource was not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User information retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    searchWeather: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filters: components["schemas"]["WeatherFilters"];
                    dateRange: components["schemas"]["DateRange"];
                    options?: {
                        /**
                         * @description Maximum number of results to return
                         * @default 50
                         */
                        limit?: number;
                        /**
                         * @description Minimum match score to include in results
                         * @default 0
                         */
                        minScore?: number;
                        /**
                         * @description Limit search to a specific region
                         * @enum {string}
                         */
                        region?: "northeast" | "southeast" | "midwest" | "southwest" | "west" | "pacific_northwest";
                        /** @description Limit search to specific states (2-letter codes) */
                        states?: string[];
                    };
                };
            };
        };
        responses: {
            /** @description Search completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            results?: components["schemas"]["WeatherSearchResult"][];
                            meta?: {
                                /** @description Total grid points searched */
                                totalGridPoints?: number;
                                /** @description Grid points meeting minimum score */
                                matchingPoints?: number;
                                /** @enum {string} */
                                dataSource?: "forecast" | "historical" | "mixed";
                                /** @description Days covered by forecast data */
                                forecastDays?: number;
                                /** @description Days covered by historical data */
                                historicalDays?: number;
                                /** @description Warning message for long date ranges (31-90 days) */
                                warning?: string;
                            };
                        };
                    };
                };
            };
            /** @description Invalid request parameters or date range too large */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimitError"];
        };
    };
    getGridPoints: {
        parameters: {
            query?: {
                /** @description Filter by geographic region */
                region?: "northeast" | "southeast" | "midwest" | "southwest" | "west" | "pacific_northwest";
                /** @description Filter by states (comma-separated 2-letter codes) */
                states?: string[];
                /**
                 * @description Bounding box as "minLat,minLon,maxLat,maxLon" to get grid points
                 *     within a map viewport. Example: "32.0,-115.0,37.0,-109.0"
                 */
                bounds?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grid points retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            gridPoints?: components["schemas"]["GridPoint"][];
                            total?: number;
                        };
                    };
                };
            };
            429: components["responses"]["RateLimitError"];
        };
    };
    getGridPointWeather: {
        parameters: {
            query: {
                /** @description Start date (ISO 8601) */
                startDate: string;
                /** @description End date (ISO 8601) */
                endDate: string;
            };
            header?: never;
            path: {
                /** @description Grid point ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Weather data retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            gridPoint?: components["schemas"]["GridPoint"];
                            dailyData?: components["schemas"]["DailyWeather"][];
                            summary?: {
                                avgTempHigh?: number;
                                avgTempLow?: number;
                                avgHumidity?: number;
                                avgWindSpeed?: number;
                                avgPrecipChance?: number;
                                avgAqi?: number;
                            };
                        };
                    };
                };
            };
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["RateLimitError"];
        };
    };
    findNearestGridPoint: {
        parameters: {
            query: {
                /** @description Latitude in decimal degrees */
                lat: number;
                /** @description Longitude in decimal degrees */
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nearest grid point found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            gridPoint?: components["schemas"]["GridPoint"];
                            /** @description Distance from requested coordinates in miles */
                            distance?: number;
                        };
                    };
                };
            };
            /** @description Coordinates outside USA coverage area */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSavedSearches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Searches retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            searches?: components["schemas"]["SavedSearch"][];
                        };
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createSavedSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Spring 2025 Southwest Trip */
                    title: string;
                    filters: components["schemas"]["WeatherFilters"];
                    dateRange: components["schemas"]["DateRange"];
                };
            };
        };
        responses: {
            /** @description Search saved successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["SavedSearch"];
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            429: components["responses"]["RateLimitError"];
        };
    };
    getSavedSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["SavedSearch"];
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateSavedSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    filters?: components["schemas"]["WeatherFilters"];
                    dateRange?: components["schemas"]["DateRange"];
                };
            };
        };
        responses: {
            /** @description Search updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["SavedSearch"];
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["RateLimitError"];
        };
    };
    deleteSavedSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        /** @example Search deleted successfully */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getElectricalConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configurations retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            configs?: components["schemas"]["ElectricalConfig"][];
                        };
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createElectricalConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Dream Build */
                    title: string;
                    configData: components["schemas"]["ElectricalConfigData"];
                };
            };
        };
        responses: {
            /** @description Configuration created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["ElectricalConfig"];
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            429: components["responses"]["RateLimitError"];
        };
    };
    getElectricalConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["ElectricalConfig"];
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateElectricalConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    configData?: components["schemas"]["ElectricalConfigData"];
                };
            };
        };
        responses: {
            /** @description Configuration updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["ElectricalConfig"];
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["RateLimitError"];
        };
    };
    deleteElectricalConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        /** @example Configuration deleted successfully */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getResources: {
        parameters: {
            query?: {
                /** @description Filter by category */
                category?: components["schemas"]["ResourceCategory"];
                /** @description Search in title and description */
                search?: string;
                /** @description Page number */
                page?: number;
                /** @description Results per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resources retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: {
                            resources?: components["schemas"]["Resource"][];
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            429: components["responses"]["RateLimitError"];
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"] & {
                        data?: components["schemas"]["Resource"];
                    };
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
}
